import test from 'node:test';import assert from 'node:assert/strict';
import {initialState,applyOperations,clone,checkPrecondition} from '../src/domain-state.mjs';
import {actorState} from '../src/actor-view.mjs';
import {compileContext} from '../src/model.mjs';
const initial=()=>initialState({name:'甲',extensions:{story_runtime:{characters:[{id:'b',name:'乙',location:'森林'}],variables:{publicValue:1}}}});
test('host assigns new stable entity IDs and directed relationships can be revised/ended with evidence',()=>{const s=initial();applyOperations(s,[{op:'create_entity',name:'李明',kind:'character',aliases:['小李']},{op:'create_entity',name:'行会',kind:'organization'}],{commitId:'c1',author:true});const person=s.characters.find(x=>x.name==='李明'),org=s.characters.find(x=>x.name==='行会');assert.ok(person.id&&person.id!==person.name);applyOperations(s,[{op:'add_relation',from:person.id,to:org.id,type:'member_of',detail:'学徒'}],{commitId:'c2'});const rel=s.relations[0];applyOperations(s,[{op:'update_relation',id:rel.id,detail:'正式成员',addressFrom:'师傅',locked:true}],{commitId:'c3',author:true});assert.equal(rel.sourceCommitId,'c3');assert.equal(rel.detail,'正式成员');assert.throws(()=>applyOperations(clone(s),[{op:'end_relation',id:rel.id}],{commitId:'c4'}),{code:'LOCKED_FIELD'});applyOperations(s,[{op:'end_relation',id:rel.id}],{commitId:'c4',author:true});assert.equal(rel.status,'ended');assert.equal(rel.validUntil,s.time);});
test('actor views filter every newly private collection and use beliefs rather than world locations',()=>{const s=initial();applyOperations(s,[{op:'set_belief',holderId:'card-main',subjectId:'b',key:'location',value:'码头'},{op:'add_relation',from:'player',to:'b',type:'SECRET_REL',visibility:'private',holderId:'player'},{op:'change_inventory',entityId:'player',item:'SECRET_ITEM',amount:1,visibility:'private',holderId:'player'},{op:'set_variable',key:'secret',value:'SECRET_VAR',visibility:'private',holderId:'player'},{op:'update_entity',id:'b',description:'SECRET_DESCRIPTION',descriptionVisibility:'private'}],{commitId:'c',author:true});const a=actorState(s,'card-main');assert.equal(a.characters.find(x=>x.id==='b').location,'码头');for(const secret of ['SECRET_REL','SECRET_ITEM','SECRET_VAR','SECRET_DESCRIPTION'])assert.ok(!JSON.stringify(a).includes(secret));assert.ok(JSON.stringify(actorState(s,'player')).includes('SECRET_VAR'));});
test('observation updates cognition without changing truth and NPC condition follows mistaken knowledge',()=>{const s=initial();applyOperations(s,[{op:'set_belief',holderId:'card-main',subjectId:'b',key:'location',value:'码头'}],{commitId:'rumor'});const condition={belief:{subjectId:'b',key:'location',equals:'码头'}};assert.equal(checkPrecondition(s,condition,'card-main'),true);applyOperations(s,[{op:'observe',holderId:'card-main',subjectId:'b',key:'location',value:'森林',kind:'observation'}],{commitId:'seen'});assert.equal(checkPrecondition(s,condition,'card-main'),false);assert.equal(s.characters.find(x=>x.id==='b').location,'森林');assert.equal(s.beliefs[0].sourceCommitId,'seen');});
test('NPC model context cannot reuse player-private narrative or other actor secrets',()=>{const s=initial();applyOperations(s,[{op:'set_belief',holderId:'card-main',subjectId:'b',key:'location',value:'码头'}],{commitId:'belief'});const snapshot={world:{id:'w',card:{name:'甲'}},branch:{id:'b',sourceRevision:'v'},state:s,scenes:[{id:'private-scene',userText:'PLAYER_PRIVATE_INPUT',narrative:'PLAYER_PRIVATE_NARRATIVE',operations:[]}],runs:[],usage:[]};const text=JSON.stringify(compileContext(snapshot,'该去哪里？',{actorId:'card-main'}));assert.ok(text.includes('码头'));assert.ok(!text.includes('PLAYER_PRIVATE'));assert.ok(!text.includes('森林'));});

test('real schedule acts on mistaken NPC belief until observation invalidates its next action',async t=>{
 const {WorldStore}=await import('../src/store.mjs');const {mkdtempSync,rmSync}=await import('node:fs');const {join}=await import('node:path');const {tmpdir}=await import('node:os');const dir=mkdtempSync(join(tmpdir(),'cognitive-schedule-'));const store=new WorldStore(dir);t.after(()=>{store.close();rmSync(dir,{recursive:true,force:true});});let s=store.createWorld({name:'认知闭环',card:{name:'甲',extensions:{story_runtime:{characters:[{id:'b',name:'乙',location:'森林'}]}}}});
 const commit=ops=>s=store.commit({worldId:s.world.id,branchId:s.branch.id,expectedHead:s.branch.head,sourceRevision:s.branch.sourceRevision,runId:crypto.randomUUID(),userText:'',narrative:'记录有来源的认知与安排。',operations:ops,author:true}).snapshot;
 commit([{op:'set_belief',holderId:'card-main',subjectId:'b',key:'location',value:'码头'},{op:'schedule',at:1,entityId:'card-main',label:'按约定去码头找乙',precondition:{belief:{subjectId:'b',key:'location',equals:'码头'}},operations:[{op:'set_location',entityId:'card-main',value:'码头'}]}]);store.advance({worldId:s.world.id,branchId:s.branch.id,to:1,maxEvents:10});s=store.snapshot(s.world.id,s.branch.id);assert.equal(s.state.characters.find(x=>x.id==='card-main').location,'码头');assert.equal(s.state.characters.find(x=>x.id==='b').location,'森林');
 commit([{op:'schedule',at:2,entityId:'card-main',label:'继续等乙',precondition:{belief:{subjectId:'b',key:'location',equals:'码头'}},operations:[{op:'set_location',entityId:'card-main',value:'码头内厅'}]},{op:'observe',holderId:'card-main',subjectId:'b',key:'location',value:'森林',kind:'observation'}]);const result=store.advance({worldId:s.world.id,branchId:s.branch.id,to:2,maxEvents:10});assert.equal(result.cancelled.length,1);assert.equal(store.snapshot(s.world.id,s.branch.id).state.characters.find(x=>x.id==='card-main').location,'码头');assert.equal(store.snapshot(s.world.id,s.branch.id).usage.length,0);
});
