import {applyOperations} from '../src/domain-state.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import {renderTemplate,runBehaviors,applyTextRules,behaviorReport} from '../src/behavior.mjs';
const state=()=>({time:0,characters:[{id:'player',name:'甲'},{id:'b',name:'乙'}],relations:[],facts:[],beliefs:[],goals:[],inventory:[],variables:{trust:1},schedules:[],plotThreads:[]});
test('native loops, scoped variables, nested conditionals and previews are bounded/pure',()=>{const s=state(),before=JSON.stringify(s),card={name:'旅人'};assert.equal(renderTemplate('{{#each characters}}{{name}}:{{id}};{{/each}} {{#if trust}}{{char}} {{getvar::trust}}{{/if}}',{card,state:s}),'甲:player;乙:b; 旅人 1');assert.equal(JSON.stringify(s),before);assert.equal(renderTemplate('{{#if missing}}bad{{else}}ok{{/if}}',{card,state:s}),'ok');assert.throws(()=>renderTemplate('{{#each characters}}oops',{card,state:s}),{code:'TEMPLATE_SYNTAX'});});
test('lifecycle proposals stage variables without mutating canon and post-commit cannot write',()=>{const s=state(),card={extensions:{story_runtime:{rules:[{event:'input',when:{variable:'trust',equals:1},operations:[{op:'increment_variable',key:'trust',amount:2}]},{event:'before_generate',append:'信任={{getvar::trust}}'}]}}};const first=runBehaviors(card,s,'input','你好');assert.equal(s.variables.trust,1);assert.equal(first.state.variables.trust,3);assert.equal(first.operations.length,1);const next=runBehaviors(card,first.state,'before_generate',first.text);assert.equal(next.text,'你好\n信任=3');assert.throws(()=>runBehaviors({extensions:{story_runtime:{rules:[{event:'post_commit',operations:[{op:'set_variable',key:'x',value:1}]}]}}},s,'post_commit',''),{code:'BEHAVIOR_STAGE'});});
test('input/output/display regular-expression stages are ordered and display cannot change evidence',()=>{const rules=[{stage:'input',pattern:'hello',replacement:'你好',flags:'gi'},{stage:'model_output',pattern:'world',replacement:'世界'},{stage:'display',pattern:'世界',replacement:'【世界】'}];assert.equal(applyTextRules('HELLO world',rules,'input'),'你好 world');const canonical=applyTextRules('world',rules,'model_output');assert.equal(canonical,'世界');assert.equal(applyTextRules(canonical,rules,'display'),'【世界】');assert.equal(canonical,'世界');});
test('unsupported regex constructs and invalid writes are explicitly rejected/reported',()=>{for(const pattern of ['a+','(a)','a|b','\\1'])assert.throws(()=>applyTextRules('sample',[{stage:'input',pattern,replacement:''}],'input'),{code:'REGEX_UNSUPPORTED'});const report=behaviorReport({extensions:{story_runtime:{textRules:[{stage:'input',pattern:'a+',replacement:''}]}}});assert.equal(report[0].status,'unsupported');assert.ok(report[0].field.includes('textRules'));});

test('real HTTP lifecycle stages commit once, cancellation leaves staged variables unchanged',async t=>{
 const {startServer}=await import('../src/server.mjs');const {mkdtemp,rm}=await import('node:fs/promises');const {join}=await import('node:path');const {tmpdir}=await import('node:os');const dir=await mkdtemp(join(tmpdir(),'story-behavior-'));const server=await startServer({dataDir:dir,port:0,demoDelay:20,env:{}});t.after(async()=>{await server.close();await rm(dir,{recursive:true,force:true});});
 const call=async(path,data,status=200)=>{const r=await fetch(server.url+path,data?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)}:undefined);assert.equal(r.status,status);return r.json();};
 const card={name:'测试角色',extensions:{story_runtime:{variables:{trust:0},rules:[{event:'input',operations:[{op:'increment_variable',key:'trust',amount:1}]},{event:'post_commit',append:'ONLY_AFTER_COMMIT'}],textRules:[{stage:'display',pattern:'测试角色',replacement:'角色（显示）'}]}}};
 const imported=await call('/api/import',{filename:'behavior.json',base64:Buffer.from(JSON.stringify(card)).toString('base64')},201);let s=await call('/api/worlds',{cardId:imported.card.id},201);const p='/api/worlds/'+s.world.id,request={branchId:s.branch.id,message:'你好',mode:'demo',runId:'staged-turn'};
 const r=await call(p+'/turn',request,202);const events=await(await fetch(server.url+'/api/runs/'+r.runId+'/events')).text();assert.equal((events.match(/ONLY_AFTER_COMMIT/g)||[]).length,1);s=await call(p);assert.equal(s.state.variables.trust,1);assert.ok(s.scenes[0].narrative.includes('测试角色'));assert.ok(s.scenes[0].displayNarrative.includes('角色（显示）'));
 await call(p+'/turn',request,202);assert.equal((await call(p)).state.variables.trust,1);
 const pending=await call(p+'/turn',{...request,runId:'cancel-turn'},202);await call('/api/runs/'+pending.runId+'/cancel',{});await(await fetch(server.url+'/api/runs/'+pending.runId+'/events')).text();assert.equal((await call(p)).state.variables.trust,1);
});

test('legacy import normalization stays recoverable and does not silently enable newly mapped behavior',async t=>{
 const {importCard}=await import('../src/importer.mjs');const {WorldStore}=await import('../src/store.mjs');const {createBackup,restoreBackup}=await import('../src/backup.mjs');const {mkdtemp,writeFile,rm}=await import('node:fs/promises');const {join}=await import('node:path');const {tmpdir}=await import('node:os');const root=await mkdtemp(join(tmpdir(),'legacy-behavior-'));let store;t.after(async()=>{store?.close();await rm(root,{recursive:true,force:true});});
 const card={name:'旧卡',extensions:{story_runtime:{variables:{trust:1},rules:[{event:'input',operations:[{op:'increment_variable',key:'trust',amount:1}]}]}}};const imported=await importCard({filename:'old.json',bytes:Buffer.from(JSON.stringify(card)),dataDir:join(root,'data'),normalizerVersion:1});store=new WorldStore(join(root,'data'));const world=store.createWorld({name:'旧世界',card:imported.card});assert.equal(runBehaviors(imported.card,world.state,'input','你好').state.variables.trust,1);
 const backup=await createBackup(store,join(root,'data')),path=join(root,'backup.json');await writeFile(path,JSON.stringify(backup));await restoreBackup(path,join(root,'restored'));const reopened=new WorldStore(join(root,'restored'));try{assert.equal(reopened.snapshot(world.world.id).world.card.extensions._import.normalizerVersion,undefined);}finally{reopened.close();}
});

test('lifecycle append and condition cannot read private variables through an indirect prompt',()=>{const s=state();s.variables.secret='NEVER_MODEL_SECRET';s.variableVisibility={secret:{visibility:'private',holderId:'b'}};const card={extensions:{story_runtime:{rules:[{event:'before_generate',append:'{{getvar::secret}}'},{event:'before_generate',when:{variable:'secret',equals:'NEVER_MODEL_SECRET'},append:'SECRET_CONDITION_WAS_TRUE'}]}}};const r=runBehaviors(card,s,'before_generate','continue');assert.equal(r.text,'continue\n');assert.ok(!r.text.includes('SECRET'));});

test('card/world/scene variable namespaces are distinct; scene writes are discarded at commit',()=>{const s=state();const card={name:'甲',extensions:{story_runtime:{rules:[{event:'input',operations:[{op:'set_variable',scope:'card',key:'value',value:'卡片'},{op:'set_variable',key:'value',value:'世界'},{op:'set_variable',scope:'scene',key:'value',value:'暂存'}]},{event:'before_generate',append:'{{getvar::card::value}}/{{getvar::value}}/{{getvar::scene::value}}'}]}}};const staged=runBehaviors(card,s,'input','');const before=runBehaviors(card,staged.state,'before_generate','');assert.equal(before.text,'卡片/世界/暂存');assert.equal(s.variables.value,undefined);applyOperations(s,staged.operations,{commitId:'commit'});assert.equal(s.cardVariables.value,'卡片');assert.equal(s.variables.value,'世界');assert.equal(s.sceneVariables,undefined);});
