import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {WorldStore} from '../src/store.mjs';
import {knowledgeBundle,searchKnowledge,chapterSummaries} from '../src/knowledge.mjs';
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'story-knowledge-'));let store=new WorldStore(dir);t.after(()=>{store.close();rmSync(dir,{recursive:true,force:true});});let s=store.createWorld({name:'渡口',card:{name:'李明',extensions:{story_runtime:{characters:[{id:'npc',name:'李明',description:'另一位李明'}]}}}});return {get store(){return store;},reopen(){store.close();store=new WorldStore(dir);},get s(){return s;},commit(operations,narrative='渡口发生了可追查的变化。'){s=store.commit({worldId:s.world.id,branchId:s.branch.id,sourceRevision:s.branch.sourceRevision,expectedHead:s.branch.head,runId:crypto.randomUUID(),userText:'',narrative,operations,author:true,source:'author'}).snapshot;return s;}};}
test('chapter marker and summaries survive restart and trace only current branch sources',t=>{const f=fixture(t);f.commit([{op:'mark_chapter',title:'第一章 · 渡口'}],'第一章开始。');f.commit([],'船靠岸了。');const before=f.s;f.commit([{op:'mark_chapter',title:'未来章节'}],'未来不可渗漏。');const fork=f.store.fork({worldId:f.s.world.id,branchId:f.s.branch.id,commitId:before.branch.head,name:'另一条路'});f.reopen();const chapters=chapterSummaries(f.store.snapshot(fork.world.id,fork.branch.id),'author');assert.equal(chapters.length,1);assert.equal(chapters[0].title,'第一章 · 渡口');assert.ok(chapters[0].sourceCommitIds.includes(before.branch.head));assert.ok(!JSON.stringify(chapters).includes('未来不可渗漏'));assert.match(chapters[0].method,/extractive/);});
test('knowledge export has distinct player/author views, source IDs and safe filenames',t=>{const f=fixture(t);f.commit([{op:'set_fact',key:'public',value:'渡船明早出发',visibility:'public'},{op:'set_fact',key:'secret',value:'秘密金库位置',visibility:'private',holderId:'npc'}]);const player=knowledgeBundle(f.s),author=knowledgeBundle(f.s,'author');assert.ok(!JSON.stringify(player).includes('秘密金库位置'));assert.ok(JSON.stringify(author).includes('秘密金库位置'));assert.equal(player.view,'player');assert.equal(player.headCommitId,f.s.branch.head);assert.ok(Object.keys(player.files).includes('world.md'));for(const name of Object.keys(player.files))assert.ok(!name.includes('..')&&!name.startsWith('/'));assert.ok(player.files['events.md'].includes(f.s.branch.head));});
test('short Chinese and duplicate name search returns separate stable IDs and source evidence',t=>{const f=fixture(t);f.commit([{op:'set_fact',key:'船',value:'渡船明早出发',visibility:'public'},{op:'set_fact',key:'密',value:'隐藏码头',visibility:'private',holderId:'npc'}]);const names=searchKnowledge(f.s,'李明');assert.equal(names.filter(r=>r.kind==='character').length,2);assert.equal(new Set(names.filter(r=>r.kind==='character').map(r=>r.id)).size,2);assert.ok(searchKnowledge(f.s,'船').some(r=>r.kind==='fact'&&r.sourceCommitId===f.s.branch.head));assert.ok(!JSON.stringify(searchKnowledge(f.s,'隐藏')).includes('隐藏码头'));});
test('chapter operation is author-only, bounded and cannot be used by model or schedules',t=>{const f=fixture(t);assert.throws(()=>f.store.commit({worldId:f.s.world.id,branchId:f.s.branch.id,sourceRevision:f.s.branch.sourceRevision,expectedHead:f.s.branch.head,runId:'model-chapter',userText:'',narrative:'x',operations:[{op:'mark_chapter',title:'x'}]}),{code:'AUTHOR_REQUIRED'});assert.equal(f.s.scenes.length,0);});

test('real HTTP chapter/search/export routes honor view and current branch',async t=>{
 const {startServer}=await import('../src/server.mjs');const dir=mkdtempSync(join(tmpdir(),'story-knowledge-http-'));const server=await startServer({dataDir:dir,port:0,env:{}});t.after(async()=>{await server.close();rmSync(dir,{recursive:true,force:true});});
 const call=async(path,data)=>{const r=await fetch(server.url+path,data?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)}:undefined);assert.ok(r.ok);return r.json();};
 let s=await call('/api/worlds',{name:'章节测试'});const p='/api/worlds/'+s.world.id;
 s=await call(p+'/actions',{branchId:s.branch.id,operations:[{op:'mark_chapter',title:'归来'},{op:'set_fact',key:'暗门',value:'秘密原文',visibility:'private',holderId:'card-main'}],narrative:'作者记录私有资料。',publicNarrative:'你回到了渡口。'});
 assert.equal((await call(p+'/chapters')).chapters[0].title,'归来');assert.ok(!JSON.stringify(await call(p+'/knowledge')).includes('秘密原文'));assert.ok(JSON.stringify(await call(p+'/knowledge?view=author')).includes('秘密原文'));assert.ok((await call(p+'/knowledge-search?q='+encodeURIComponent('渡口'))).results.some(r=>r.kind==='scene'));
});
