import test from 'node:test';import assert from 'node:assert/strict';
import {compileContext,demoGenerate,parseModelReply,visibleSnapshot,normalizeUsage} from '../src/model.mjs';
const snap=()=>({world:{id:'w',name:'测试',card:{name:'旅人',description:'角色设定',firstMessage:'你好',worldbook:[{keys:['钟楼'],content:'钟楼在城东',enabled:true}]}},branch:{id:'b'},state:{time:0,characters:[{id:'player',name:'玩家'}],relations:[],facts:[{id:'secret',key:'秘密',value:'绝密密码',visibility:'private',holderId:'npc'},{id:'known',key:'天色',value:'晴',visibility:'public'}],beliefs:[{holderId:'npc',value:'秘密认知'}],goals:[{visibility:'private',text:'暗中计划'}],inventory:[],variables:{},schedules:[],plotThreads:[]},scenes:[],usage:[],outbox:[]});
test('player view and model context omit private facts/beliefs/goals',()=>{const s=snap();for(const value of [JSON.stringify(visibleSnapshot(s)),JSON.stringify(compileContext(s,'去钟楼'))]){assert.ok(!value.includes('绝密密码'));assert.ok(!value.includes('暗中计划'));assert.ok(!value.includes('秘密认知'));}assert.ok(JSON.stringify(visibleSnapshot(s,'author')).includes('绝密密码'));});
test('context deterministic and literal worldbook activates with bounded content',()=>{const s=snap();assert.deepEqual(compileContext(s,'去钟楼'),compileContext(s,'去钟楼'));assert.ok(JSON.stringify(compileContext(s,'去钟楼')).includes('钟楼在城东'));assert.ok(!JSON.stringify(compileContext(s,'你好')).includes('钟楼在城东'));});
test('structured reply rejects unknown keys and invalid shapes',()=>{assert.deepEqual(parseModelReply('{"narrative":"正文","operations":[]}'),{narrative:'正文',operations:[]});for(const x of ['bad','{"narrative":"x","operations":{},"shell":"x"}','{"narrative":"","operations":[]}'])assert.throws(()=>parseModelReply(x));});
test('demo is deterministic and only moves player when explicitly asked',async()=>{const s=snap();let chunks='';const a=await demoGenerate(s,'你好',{onDelta:x=>chunks+=x,delay:0});assert.equal(a.operations.length,0);assert.equal(chunks,a.narrative);const b=await demoGenerate(s,'前往钟楼',{delay:0});assert.deepEqual(b.operations,[{op:'set_location',entityId:'player',value:'钟楼'}]);});
test('missing usage remains null, not free model call',()=>{assert.deepEqual(normalizeUsage(),{inputTokens:null,cachedInputTokens:null,outputTokens:null});assert.deepEqual(normalizeUsage({prompt_tokens:20,completion_tokens:3,prompt_tokens_details:{cached_tokens:12}}),{inputTokens:20,cachedInputTokens:12,outputTokens:3});});
import {openAIGenerate} from '../src/model.mjs';
function streamResponse(events){const bytes=new TextEncoder().encode(events);return new Response(new ReadableStream({start(c){for(let i=0;i<bytes.length;i+=7)c.enqueue(bytes.slice(i,i+7));c.close();}}),{headers:{'content-type':'text/event-stream'}});}
const config={configured:true,url:'http://127.0.0.1/v1/chat/completions',model:'local-mock',key:'fixture',stream:true,maxTokens:300};
test('real SSE parser accepts split UTF8/JSON, finish and empty choices usage tail',async()=>{let displayed='';const content=JSON.stringify({narrative:'钟楼的灯亮了。',operations:[]});const chunks=[content.slice(0,16),content.slice(16,21),content.slice(21)];const text=chunks.map(c=>'data: '+JSON.stringify({choices:[{delta:{content:c}}]})+'\r\n\r\n').join('')+'data: '+JSON.stringify({choices:[{delta:{},finish_reason:'stop'}]})+'\n\ndata: '+JSON.stringify({choices:[],usage:{prompt_tokens:50,completion_tokens:8,prompt_tokens_details:{cached_tokens:30}}})+'\n\ndata: [DONE]\n\n';const result=await openAIGenerate(snap(),'你好',{config,fetchImpl:async()=>streamResponse(text),onDraft:x=>displayed=x});assert.equal(result.narrative,'钟楼的灯亮了。');assert.equal(displayed,result.narrative);assert.deepEqual(result.usage,{inputTokens:50,cachedInputTokens:30,outputTokens:8});});
test('SSE incomplete and length-truncated replies never return a commit proposal',async()=>{const payload=JSON.stringify({narrative:'尚未提交',operations:[]});for(const end of ['', 'data: '+JSON.stringify({choices:[{finish_reason:'length',delta:{}}]})+'\n\ndata: [DONE]\n\n']){const text='data: '+JSON.stringify({choices:[{delta:{content:payload}}]})+'\n\n'+end;await assert.rejects(openAIGenerate(snap(),'继续',{config,fetchImpl:async()=>streamResponse(text)}),{code:end?'MODEL_TRUNCATED':'MODEL_INCOMPLETE'});}});
test('provider error details do not leak secret-like text to UI errors',async()=>{await assert.rejects(openAIGenerate(snap(),'继续',{config,fetchImpl:async()=>new Response('credential=private',{status:401})}),e=>e.code==='MODEL_HTTP'&&!e.message.includes('private'));});
test('player cannot read private updates by id, nested scheduled proposals or unplanted plot hints',()=>{const s=snap();s.state.plotThreads=[{id:'plot',label:'UNPLANTED_SENTINEL',status:'planned'}];s.state.schedules=[{id:'n',entityId:'npc',label:'SECRET_SCHEDULE_LABEL',operations:[]}];s.scenes=[{id:'c',userText:'',narrative:'作者调整了设定',source:'author',operations:[{op:'set_fact',id:'secret',value:'ID_UPDATE_SECRET'},{op:'schedule',label:'x',operations:[{op:'set_fact',visibility:'private',value:'NESTED_SECRET'}]}]}];for(const text of [JSON.stringify(visibleSnapshot(s)),JSON.stringify(compileContext(s,'继续'))])for(const secret of ['ID_UPDATE_SECRET','NESTED_SECRET','UNPLANTED_SENTINEL','SECRET_SCHEDULE_LABEL'])assert.ok(!text.includes(secret),secret);});
test('NPC truth location does not silently become player belief; hidden schedule outcomes remain private',()=>{const s=snap();s.state.characters.push({id:'npc',name:'NPC',location:'HIDDEN_LOCATION'});s.scenes.push({id:'autonomous',source:'schedule',narrative:'HIDDEN_NPC_PLAN',operations:[{op:'set_location',entityId:'npc',value:'HIDDEN_LOCATION'}]});const shown=visibleSnapshot(s);assert.equal(shown.state.characters.find(x=>x.id==='npc').location,null);assert.ok(!JSON.stringify(compileContext(s,'继续')).includes('HIDDEN_LOCATION'));assert.ok(!JSON.stringify(shown).includes('HIDDEN_NPC_PLAN'));s.state.beliefs.push({holderId:'player',subjectId:'npc',key:'location',value:'旧位置'});assert.equal(visibleSnapshot(s).state.characters.find(x=>x.id==='npc').location,'旧位置');});
import {publicDraft} from '../src/model.mjs';
test('failed, cancelled and interrupted model runs retain public narrative draft',()=>{for(const status of ['failed','cancelled','interrupted'])assert.equal(publicDraft({mode:'openai',status,draft:'已识别但未提交的正文'}),'已识别但未提交的正文');});
test('large character descriptions cannot truncate structured current-state JSON',()=>{const s=snap();s.state.characters[0].description='x'.repeat(25000);s.state.variables={visible:2};const messages=compileContext(s,'继续');const dynamic=messages.find(x=>x.content.startsWith('本轮公开状态'));const raw=dynamic.content.split('\n')[1];const state=JSON.parse(raw);assert.equal(state.variables.visible,2);assert.equal(state.facts[0].value,'晴');assert.ok(raw.length<21000);});
test('bounded native conditional and variable template preview is pure',()=>{const s=snap();s.world.card.description='{{char}}：{{#if trust}}信任 {{getvar::trust}}{{else}}初次见面{{/if}}';s.state.variables={trust:2};const before=JSON.stringify(s);assert.ok(JSON.stringify(compileContext(s,'你好')).includes('信任 2'));assert.equal(JSON.stringify(s),before);s.state.variables.trust=0;assert.ok(JSON.stringify(compileContext(s,'你好')).includes('初次见面'));});
test('scheduled private update cannot collide with same public key/other holder or later declassification',()=>{const s=snap();s.state.facts=[{id:'pub',key:'same',value:'public',visibility:'public',holderId:null},{id:'priv',key:'same',value:'PRIVATE_UPDATED',visibility:'private',holderId:'card-main'}];s.scenes=[{id:'sched',source:'schedule',narrative:'private label',operations:[{op:'set_fact',key:'same',holderId:'card-main',value:'PRIVATE_UPDATED'}]}];for(const view of [JSON.stringify(visibleSnapshot(s)),JSON.stringify(compileContext(s,'继续'))])assert.ok(!view.includes('PRIVATE_UPDATED'));s.state.facts[1].visibility='public';s.state.facts[1].value='new public value';assert.ok(!JSON.stringify(compileContext(s,'继续')).includes('PRIVATE_UPDATED'));});
test('selected opening is available to first-turn model as imported material and pure UI preview',()=>{const a=snap(),b=snap();a.world.card.firstMessage='GREETING_A 选择第一或第二';b.world.card.firstMessage='GREETING_B 欢迎{{user}}，{{char}}在这里';assert.ok(JSON.stringify(compileContext(a,'选第一')).includes('GREETING_A'));assert.ok(JSON.stringify(compileContext(b,'选第一')).includes('GREETING_B'));assert.notDeepEqual(compileContext(a,'选第一'),compileContext(b,'选第一'));assert.equal(visibleSnapshot(b).world.card.openingPreview,'GREETING_B 欢迎玩家，旅人在这里');assert.equal(b.scenes.length,0);});

test('bounded context checkpoint freezes per epoch and revision/fork excludes withdrawn history',()=>{const s=snap();s.branch.sourceRevision='rev1';s.scenes=Array.from({length:65},(_,i)=>({id:'scene-'+i,userText:'',narrative:'事件 '+i,operations:[]}));const a=compileContext(s,'继续'),checkpoint=a.find(x=>x.content.startsWith('上下文检查点'));assert.ok(checkpoint);assert.ok(checkpoint.content.includes('scene-39'));s.scenes.push({id:'scene-65',narrative:'新事件',userText:'',operations:[]});assert.equal(compileContext(s,'继续').find(x=>x.content.startsWith('上下文检查点')).content,checkpoint.content);const fork=snap();fork.branch.id='fork';fork.scenes=s.scenes.slice(0,5);assert.ok(!JSON.stringify(compileContext(fork,'继续')).includes('事件 64'));});

test('first response and idle timeouts are distinct; active streams have no fixed total cutoff',async t=>{const {createServer}=await import('node:http');const content=JSON.stringify({narrative:'持续的正常输出',operations:[]});const server=createServer((req,res)=>{if(req.url==='/first')return;res.writeHead(200,{'content-type':'text/event-stream'});res.write(': ready\n\n');if(req.url==='/idle')return;let i=0;const timer=setInterval(()=>{if(i<content.length)res.write('data: '+JSON.stringify({choices:[{delta:{content:content.slice(i,i+=8)}}]})+'\n\n');else{clearInterval(timer);res.end('data: [DONE]\n\n');}},8);res.on('close',()=>clearInterval(timer));});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();server.close();});const base='http://127.0.0.1:'+server.address().port;
 await assert.rejects(openAIGenerate(snap(),'继续',{config:{...config,url:base+'/first',firstResponseMs:25,idleTimeoutMs:25}}),{code:'MODEL_FIRST_RESPONSE_TIMEOUT'});
 await assert.rejects(openAIGenerate(snap(),'继续',{config:{...config,url:base+'/idle',firstResponseMs:100,idleTimeoutMs:25}}),{code:'MODEL_IDLE_TIMEOUT'});
 const r=await openAIGenerate(snap(),'继续',{config:{...config,url:base+'/active',firstResponseMs:100,idleTimeoutMs:40}});assert.equal(r.narrative,'持续的正常输出');
});
